from card import Card
Buckler = Card("Buckler") 
Death_Mark = Card("Death Mark") 
Death_Mark.getsBuiltFrom(Buckler) 
Cover = Card("Cover") 
Cover.getsBuiltFrom(Buckler) 
Sharp_Arrow = Card("Sharp Arrow") 
Clockwork_Arrow = Card("Clockwork Arrow") 
Clockwork_Arrow.getsBuiltFrom(Sharp_Arrow) 
Rogue_Tactics = Card("Rogue Tactics") 
Rogue_Tactics.getsBuiltFrom(Sharp_Arrow) 
Shakedown = Card("Shakedown") 
Shakedown.getsBuiltFrom(Sharp_Arrow) 
Bonk = Card("Bonk") 
Persevere = Card("Persevere") 
Persevere.getsBuiltFrom(Bonk) 
Flash = Card("Flash") 
Flash.getsBuiltFrom(Bonk) 
Bling = Card("Bling") 
Bling.getsBuiltFrom(Bonk) 
Bottomless_Purse = Card("Bottomless Purse") 
Salve = Card("Salve") 
Salve.getsBuiltFrom(Bottomless_Purse) 
Diversify = Card("Diversify") 
Diversify.getsBuiltFrom(Bottomless_Purse) 
Overexertion = Card("Overexertion") 
Overexertion.getsBuiltFrom(Bottomless_Purse) 
Bouncy_Bomb = Card("Bouncy Bomb") 
Flashbang_Bomb = Card("Flashbang Bomb") 
Flashbang_Bomb.getsBuiltFrom(Bouncy_Bomb) 
Buster_Bomb = Card("Buster Bomb") 
Buster_Bomb.getsBuiltFrom(Bouncy_Bomb) 
Caltrops = Card("Caltrops") 
Sick_and_Tired_Arrow = Card("Sick and Tired Arrow") 
Sick_and_Tired_Arrow.getsBuiltFrom(Caltrops) 
Sharp_Rain = Card("Sharp Rain") 
Sharp_Rain.getsBuiltFrom(Caltrops) 
Hamstring = Card("Hamstring") 
Hamstring.getsBuiltFrom(Caltrops) 
Rogue_Knuckles = Card("Rogue Knuckles") 
Rogue_Knuckles.getsBuiltFrom(Clockwork_Arrow) 
Sharp_Rain.getsBuiltFrom(Clockwork_Arrow) 
Multi_Arrow = Card("Multi Arrow") 
Multi_Arrow.getsBuiltFrom(Clockwork_Arrow) 
Fortify = Card("Fortify") 
Fortify.getsBuiltFrom(Cover) 
Persevere.getsBuiltFrom(Cover) 
Mad_Skills = Card("Mad Skills") 
Mad_Skills.getsBuiltFrom(Cover) 
Chainshirt = Card("Chainshirt") 
Chainshirt.getsBuiltFrom(Death_Mark) 
Enchufla = Card("Enchufla") 
Enchufla.getsBuiltFrom(Death_Mark) 
Paint_Balloon = Card("Paint Balloon") 
Paint_Balloon.getsBuiltFrom(Death_Mark) 
Eagle_trick = Card("Eagle trick") 
Cornucopia = Card("Cornucopia") 
Cornucopia.getsBuiltFrom(Eagle_trick) 
Diversify.getsBuiltFrom(Eagle_trick) 
Overexertion.getsBuiltFrom(Eagle_trick) 
Eagles_Eye = Card("Eagles Eye") 
Ivy_Extract = Card("Ivy Extract") 
Ivy_Extract.getsBuiltFrom(Eagles_Eye) 
Garbage_Day = Card("Garbage Day") 
Garbage_Day.getsBuiltFrom(Eagles_Eye) 
Perfect_Balance = Card("Perfect Balance") 
Perfect_Balance.getsBuiltFrom(Eagles_Eye) 
Improvise = Card("Improvise") 
Rogue_Knuckles.getsBuiltFrom(Improvise) 
Throw_Knives = Card("Throw Knives") 
Throw_Knives.getsBuiltFrom(Improvise) 
Blindsided = Card("Blindsided") 
Blindsided.getsBuiltFrom(Improvise) 
Kick = Card("Kick") 
Gancho = Card("Gancho") 
Gancho.getsBuiltFrom(Kick) 
Enchufla.getsBuiltFrom(Kick) 
Flash.getsBuiltFrom(Kick) 
Knockback = Card("Knockback") 
Deadly_Roulette = Card("Deadly Roulette") 
Deadly_Roulette.getsBuiltFrom(Knockback) 
Too_old_for_this = Card("Too old for this") 
Too_old_for_this.getsBuiltFrom(Knockback) 
Damocles_Sword = Card("Damocles Sword") 
Damocles_Sword.getsBuiltFrom(Knockback) 
Loaded_Die = Card("Loaded Die") 
Entrench = Card("Entrench") 
Entrench.getsBuiltFrom(Loaded_Die) 
Cornucopia.getsBuiltFrom(Loaded_Die) 
Paint_Balloon.getsBuiltFrom(Loaded_Die) 
Luck = Card("Luck") 
Overexertion.getsBuiltFrom(Luck) 
Entrench.getsBuiltFrom(Luck) 
Adapt = Card("Adapt") 
Adapt.getsBuiltFrom(Luck) 
Mastery = Card("Mastery") 
Perfect_Balance.getsBuiltFrom(Mastery) 
Garbage_Day.getsBuiltFrom(Mastery) 
Ivy_Extract.getsBuiltFrom(Mastery) 
Mordhau = Card("Mordhau") 
Lash_out = Card("Lash out") 
Lash_out.getsBuiltFrom(Mordhau) 
Sick_and_Tired_Arrow.getsBuiltFrom(Mordhau) 
Scissor_strike = Card("Scissor strike") 
Scissor_strike.getsBuiltFrom(Mordhau) 
Osoto_Gari = Card("Osoto Gari") 
Flash.getsBuiltFrom(Osoto_Gari) 
Gancho.getsBuiltFrom(Osoto_Gari) 
Mad_Skills.getsBuiltFrom(Osoto_Gari) 
Payback = Card("Payback") 
Chainshirt.getsBuiltFrom(Payback) 
Flash.getsBuiltFrom(Payback) 
Bling.getsBuiltFrom(Payback) 
Precision_Bomb = Card("Precision Bomb") 
Buster_Bomb.getsBuiltFrom(Precision_Bomb) 
Flashbang_Bomb.getsBuiltFrom(Precision_Bomb) 
Quiver = Card("Quiver") 
Diversify.getsBuiltFrom(Quiver) 
Adapt.getsBuiltFrom(Quiver) 
Risky_Draw = Card("Risky Draw") 
Risky_Draw.getsBuiltFrom(Quiver) 
Throw_Knives.getsBuiltFrom(Rogue_Tactics) 
Blindsided.getsBuiltFrom(Rogue_Tactics) 
Lash_out.getsBuiltFrom(Rogue_Tactics) 
Trickle_down = Card("Trickle down") 
Trickle_down.getsBuiltFrom(Shakedown) 
Hamstring.getsBuiltFrom(Shakedown) 
Throw_Knives.getsBuiltFrom(Shakedown) 
Teamwork = Card("Teamwork") 
Fortify.getsBuiltFrom(Teamwork) 
Salve.getsBuiltFrom(Teamwork) 
Adapt.getsBuiltFrom(Teamwork) 
Rallying_cry = Card("Rallying cry") 
Rallying_cry.getsBuiltFrom(Adapt) 
Finesse = Card("Finesse") 
Finesse.getsBuiltFrom(Adapt) 
Tinker = Card("Tinker") 
Tinker.getsBuiltFrom(Adapt) 
Backflip = Card("Backflip") 
Porcupine = Card("Porcupine") 
Porcupine.getsBuiltFrom(Backflip) 
Shadow_Stance = Card("Shadow Stance") 
Shadow_Stance.getsBuiltFrom(Backflip) 
Barrage = Card("Barrage") 
Barrage.getsBuiltFrom(Blindsided) 
Violence = Card("Violence") 
Violence.getsBuiltFrom(Blindsided) 
Shrapnel = Card("Shrapnel") 
Shrapnel.getsBuiltFrom(Blindsided) 
Vanish = Card("Vanish") 
Vanish.getsBuiltFrom(Bling) 
Clothesline = Card("Clothesline") 
Clothesline.getsBuiltFrom(Bling) 
Breath_Control = Card("Breath Control") 
Bargain = Card("Bargain") 
Bargain.getsBuiltFrom(Breath_Control) 
Maximum_Effort = Card("Maximum Effort") 
Maximum_Effort.getsBuiltFrom(Breath_Control) 
Hot_Potato = Card("Hot Potato") 
Hot_Potato.getsBuiltFrom(Buster_Bomb) 
Shockwave_Bomb = Card("Shockwave Bomb") 
Shockwave_Bomb.getsBuiltFrom(Buster_Bomb) 
Bulwark = Card("Bulwark") 
Bulwark.getsBuiltFrom(Chainshirt) 
Clout = Card("Clout") 
Clout.getsBuiltFrom(Chainshirt) 
Dig = Card("Dig") 
Dig.getsBuiltFrom(Cornucopia) 
Bulwark.getsBuiltFrom(Cornucopia) 
Forgery_Kit = Card("Forgery Kit") 
Forgery_Kit.getsBuiltFrom(Damocles_Sword) 
Wildcard = Card("Wildcard") 
Wildcard.getsBuiltFrom(Damocles_Sword) 
Wildcard.getsBuiltFrom(Deadly_Roulette) 
Forgery_Kit.getsBuiltFrom(Deadly_Roulette) 
Finesse.getsBuiltFrom(Diversify) 
Dig.getsBuiltFrom(Diversify) 
Emergency_Tonic = Card("Emergency Tonic") 
Emergency_Tonic.getsBuiltFrom(Diversify) 
Speed = Card("Speed") 
Speed.getsBuiltFrom(Enchufla) 
Keeping_Distance = Card("Keeping Distance") 
Keeping_Distance.getsBuiltFrom(Entrench) 
Clout.getsBuiltFrom(Entrench) 
Emergency_Tonic.getsBuiltFrom(Entrench) 
Vanish.getsBuiltFrom(Flash) 
Clothesline.getsBuiltFrom(Flash) 
Shockwave_Bomb.getsBuiltFrom(Flashbang_Bomb) 
Hot_Potato.getsBuiltFrom(Flashbang_Bomb) 
Bulwark.getsBuiltFrom(Fortify) 
Copycat = Card("Copycat") 
Copycat.getsBuiltFrom(Fortify) 
Keeping_distance = Card("Keeping distance") 
Keeping_distance.getsBuiltFrom(Fortify) 
Not_Today = Card("Not Today") 
Not_Today.getsBuiltFrom(Gancho) 
Speed.getsBuiltFrom(Gancho) 
Porcupine.getsBuiltFrom(Garbage_Day) 
Bargain.getsBuiltFrom(Garbage_Day) 
Sleeve_trick = Card("Sleeve trick") 
Sleeve_trick.getsBuiltFrom(Garbage_Day) 
Violence.getsBuiltFrom(Hamstring) 
Barrage.getsBuiltFrom(Hamstring) 
Deadly_streak = Card("Deadly streak") 
Deadly_streak.getsBuiltFrom(Ivy_Extract) 
Shredder_Strike = Card("Shredder Strike") 
Shredder_Strike.getsBuiltFrom(Lash_out) 
Deflect = Card("Deflect") 
Deflect.getsBuiltFrom(Lash_out) 
Not_Today.getsBuiltFrom(Mad_Skills) 
Rallying_cry.getsBuiltFrom(Mad_Skills) 
Piercing_Arrow = Card("Piercing Arrow") 
Piercing_Arrow.getsBuiltFrom(Multi_Arrow) 
Arrow_Split = Card("Arrow Split") 
Arrow_Split.getsBuiltFrom(Multi_Arrow) 
Shrapnel.getsBuiltFrom(Multi_Arrow) 
Battle_Snack = Card("Battle Snack") 
Battle_Snack.getsBuiltFrom(Overexertion) 
Hired_help = Card("Hired help") 
Hired_help.getsBuiltFrom(Overexertion) 
Rallying_cry.getsBuiltFrom(Overexertion) 
Marked_Deck = Card("Marked Deck") 
Marked_Deck.getsBuiltFrom(Paint_Balloon) 
Clothesline.getsBuiltFrom(Paint_Balloon) 
Deadly_streak.getsBuiltFrom(Perfect_Balance) 
Sleeve_trick.getsBuiltFrom(Perfect_Balance) 
Porcupine.getsBuiltFrom(Perfect_Balance) 
Clout.getsBuiltFrom(Persevere) 
Emergency_Tonic.getsBuiltFrom(Persevere) 
Copycat.getsBuiltFrom(Persevere) 
Secret_stash = Card("Secret stash") 
Secret_stash.getsBuiltFrom(Risky_Draw) 
Dig.getsBuiltFrom(Risky_Draw) 
Tinker.getsBuiltFrom(Risky_Draw) 
Stonks = Card("Stonks") 
Stonks.getsBuiltFrom(Rogue_Knuckles) 
Shredder_Strike.getsBuiltFrom(Rogue_Knuckles) 
Battle_Snack.getsBuiltFrom(Salve) 
Finesse.getsBuiltFrom(Salve) 
Deflect.getsBuiltFrom(Scissor_strike) 
Deflect.getsBuiltFrom(Scissor_strike) 
Piercing_Arrow.getsBuiltFrom(Scissor_strike) 
Chain_shot = Card("Chain shot") 
Chain_shot.getsBuiltFrom(Sharp_Rain) 
Shrapnel.getsBuiltFrom(Sharp_Rain) 
Arrow_Split.getsBuiltFrom(Sick_and_Tired_Arrow) 
Piercing_Arrow.getsBuiltFrom(Sick_and_Tired_Arrow) 
Minesweep = Card("Minesweep") 
Minesweep.getsBuiltFrom(Throw_Knives) 
Chain_shot.getsBuiltFrom(Throw_Knives) 
Violence.getsBuiltFrom(Throw_Knives) 
Maximum_Effort.getsBuiltFrom(Too_old_for_this) 
Bargain.getsBuiltFrom(Too_old_for_this) 
Minesweep.getsBuiltFrom(Trickle_down) 
Stonks.getsBuiltFrom(Trickle_down) 
