from card import Card
Shield_Block = Card("Shield Block") 
Sword_Slash = Card("Sword Slash") 
Safeguard = Card("Safeguard") 
Safeguard.getsBuiltFrom(Shield_Block) 
Heroism = Card("Heroism") 
Heroism.getsBuiltFrom(Shield_Block) 
Tactics = Card("Tactics") 
Tactics.getsBuiltFrom(Shield_Block) 
Slam = Card("Slam") 
Slam.getsBuiltFrom(Sword_Slash) 
Short_Sword = Card("Short Sword") 
Short_Sword.getsBuiltFrom(Sword_Slash) 
Heavy_Sword = Card("Heavy Sword") 
Heavy_Sword.getsBuiltFrom(Sword_Slash) 
Akanbe = Card("Akanbe") 
Weakest_Link = Card("Weakest Link") 
Weakest_Link.getsBuiltFrom(Akanbe) 
Taunt = Card("Taunt") 
Taunt.getsBuiltFrom(Akanbe) 
Defiant_Roar = Card("Defiant Roar") 
Defiant_Roar.getsBuiltFrom(Akanbe) 
Boomerang_Shield = Card("Boomerang Shield") 
Deathblow = Card("Deathblow") 
Deathblow.getsBuiltFrom(Boomerang_Shield) 
Charge = Card("Charge") 
Charge.getsBuiltFrom(Boomerang_Shield) 
Sticks_and_Stones = Card("Sticks and Stones") 
Sticks_and_Stones.getsBuiltFrom(Boomerang_Shield) 
Camaraderie = Card("Camaraderie") 
Provoke = Card("Provoke") 
Provoke.getsBuiltFrom(Camaraderie) 
Arsenal = Card("Arsenal") 
Arsenal.getsBuiltFrom(Camaraderie) 
Barricade = Card("Barricade") 
Barricade.getsBuiltFrom(Camaraderie) 
Counter_Strike = Card("Counter Strike") 
Flow = Card("Flow") 
Flow.getsBuiltFrom(Counter_Strike) 
Snap_Back = Card("Snap Back") 
Snap_Back.getsBuiltFrom(Counter_Strike) 
Bait = Card("Bait") 
Bait.getsBuiltFrom(Counter_Strike) 
Cross_Blades = Card("Cross Blades") 
Ox = Card("Ox") 
Ox.getsBuiltFrom(Cross_Blades) 
Provoke = Card("Provoke") 
Provoke.getsBuiltFrom(Cross_Blades) 
Tap = Card("Tap") 
Tap.getsBuiltFrom(Cross_Blades) 
Fools_Guard = Card("Fools Guard") 
Padded_Shield = Card("Padded Shield") 
Padded_Shield.getsBuiltFrom(Fools_Guard) 
Mad_Snack = Card("Mad Snack") 
Mad_Snack.getsBuiltFrom(Fools_Guard) 
Elysium = Card("Elysium") 
Elysium.getsBuiltFrom(Fools_Guard) 
Deatheater_Sword = Card("Deatheater Sword") 
Deatheater_Sword.getsBuiltFrom(Heavy_Sword) 
Offering = Card("Offering") 
Offering.getsBuiltFrom(Heavy_Sword) 
Side_Sword = Card("Side Sword") 
Side_Sword.getsBuiltFrom(Heavy_Sword) 
Immutability = Card("Immutability") 
Immutability.getsBuiltFrom(Heroism) 
Pacifist = Card("Pacifist") 
Pacifist.getsBuiltFrom(Heroism) 
Barricade.getsBuiltFrom(Heroism) 
Initiative = Card("Initiative") 
Offering.getsBuiltFrom(Initiative) 
Charge.getsBuiltFrom(Initiative) 
Side_Sword.getsBuiltFrom(Initiative) 
Judgemental_Scowl = Card("Judgemental Scowl") 
Tap.getsBuiltFrom(Judgemental_Scowl) 
Taunt.getsBuiltFrom(Judgemental_Scowl) 
Defiant_Roar.getsBuiltFrom(Judgemental_Scowl) 
Mighty_Blow = Card("Mighty Blow") 
Groundbreaker = Card("Groundbreaker") 
Fury = Card("Fury") 
Fury.getsBuiltFrom(Mighty_Blow) 
Groundbreaker.getsBuiltFrom(Mighty_Blow) 
Reckless_Charge = Card("Reckless Charge") 
Reckless_Charge.getsBuiltFrom(Mighty_Blow) 
Ploughshares = Card("Ploughshares") 
Pacifist.getsBuiltFrom(Ploughshares) 
Ox.getsBuiltFrom(Ploughshares) 
Immutability.getsBuiltFrom(Ploughshares) 
Preparation = Card("Preparation") 
Knuckle_Crack = Card("Knuckle Crack") 
Knuckle_Crack.getsBuiltFrom(Preparation) 
Second_Wind = Card("Second Wind") 
Second_Wind.getsBuiltFrom(Preparation) 
Deep_Breath = Card("Deep Breath") 
Deep_Breath.getsBuiltFrom(Preparation) 
Sacrificial_Lunge = Card("Sacrificial Lunge") 
Maim = Card("Maim") 
Maim.getsBuiltFrom(Sacrificial_Lunge) 
Deathblow.getsBuiltFrom(Sacrificial_Lunge) 
All_Out_Strike = Card("All Out Strike") 
All_Out_Strike.getsBuiltFrom(Sacrificial_Lunge) 
Immutability.getsBuiltFrom(Safeguard) 
Knuckle_Crack.getsBuiltFrom(Safeguard) 
Pacifist.getsBuiltFrom(Safeguard) 
Haymaker = Card("Haymaker") 
Haymaker.getsBuiltFrom(Short_Sword) 
Maim.getsBuiltFrom(Short_Sword) 
Deatheater_Sword.getsBuiltFrom(Short_Sword) 
Single_Out = Card("Single Out") 
Weakest_Link.getsBuiltFrom(Single_Out) 
Tap.getsBuiltFrom(Single_Out) 
Defiant_Roar.getsBuiltFrom(Single_Out) 
Fury.getsBuiltFrom(Slam) 
Flurry_of_Blows = Card("Flurry of Blows") 
Flurry_of_Blows.getsBuiltFrom(Slam) 
Haymaker.getsBuiltFrom(Slam) 
Stretch = Card("Stretch") 
Second_Wind.getsBuiltFrom(Stretch) 
Knuckle_Crack.getsBuiltFrom(Stretch) 
Deep_Breath.getsBuiltFrom(Stretch) 
Swords_Akimbo = Card("Swords Akimbo") 
Deatheater_Sword.getsBuiltFrom(Swords_Akimbo) 
Whirlwind = Card("Whirlwind") 
Whirlwind.getsBuiltFrom(Swords_Akimbo) 
Groundbreaker.getsBuiltFrom(Swords_Akimbo) 
Second_Wind.getsBuiltFrom(Tactics) 
Arsenal.getsBuiltFrom(Tactics) 
Deep_Breath.getsBuiltFrom(Tactics) 
Tip_the_Scales = Card("Tip the Scales") 
Padded_Shield.getsBuiltFrom(Tip_the_Scales) 
Crown = Card("Crown") 
Crown.getsBuiltFrom(Tip_the_Scales) 
Dread = Card("Dread") 
Dread.getsBuiltFrom(Tip_the_Scales) 
Whetstone = Card("Whetstone") 
Bait.getsBuiltFrom(Whetstone) 
Lift = Card("Lift") 
Lift.getsBuiltFrom(Whetstone) 
Crown.getsBuiltFrom(Whetstone) 
Starlight_Strike = Card("Starlight Strike") 
Starlight_Strike.getsBuiltFrom(All_Out_Strike) 
Gut_Punch = Card("Gut Punch") 
Gut_Punch.getsBuiltFrom(All_Out_Strike) 
Breakthrough = Card("Breakthrough") 
Breakthrough.getsBuiltFrom(All_Out_Strike) 
The_Collector = Card("The Collector") 
The_Collector.getsBuiltFrom(Arsenal) 
Battle_Juice = Card("Battle Juice") 
Battle_Juice.getsBuiltFrom(Arsenal) 
Team_Effort = Card("Team Effort") 
Team_Effort.getsBuiltFrom(Bait) 
Thrill = Card("Thrill") 
Thrill.getsBuiltFrom(Bait) 
Insult = Card("Insult") 
Insult.getsBuiltFrom(Bait) 
Iron_Door = Card("Iron Door") 
Iron_Door.getsBuiltFrom(Barricade) 
No_Pasaran = Card("No Pasaran") 
No_Pasaran.getsBuiltFrom(Barricade) 
Diamond_Knife = Card("Diamond Knife") 
Diamond_Knife.getsBuiltFrom(Charge) 
Whack_em_All = Card("Whack em All") 
Whack_em_All.getsBuiltFrom(Charge) 
Serrated_Blade = Card("Serrated Blade") 
Serrated_Blade.getsBuiltFrom(Charge) 
Team_Effort.getsBuiltFrom(Crown) 
Thrill.getsBuiltFrom(Crown) 
Crystal_Sword = Card("Crystal Sword") 
Crystal_Sword.getsBuiltFrom(Deathblow) 
Scythe = Card("Scythe") 
Scythe.getsBuiltFrom(Deathblow) 
Double_edged_sword = Card("Double-edged sword") 
Double_edged_sword.getsBuiltFrom(Deatheater_Sword) 
Storm_of_Blades = Card("Storm of Blades") 
Storm_of_Blades.getsBuiltFrom(Deatheater_Sword) 
Crystal_Sword.getsBuiltFrom(Deatheater_Sword) 
Turtle_Up = Card("Turtle Up") 
Turtle_Up.getsBuiltFrom(Deep_Breath) 
Battle_Juice.getsBuiltFrom(Deep_Breath) 
Readiness = Card("Readiness") 
Readiness.getsBuiltFrom(Deep_Breath) 
Riddle_of_Steel = Card("Riddle of Steel") 
Riddle_of_Steel.getsBuiltFrom(Defiant_Roar) 
One_For_All = Card("One For All") 
One_For_All.getsBuiltFrom(Defiant_Roar) 
Team_Effort.getsBuiltFrom(Dread) 
Momentum = Card("Momentum") 
Momentum.getsBuiltFrom(Dread) 
Thrill.getsBuiltFrom(Dread) 
Team_Effort.getsBuiltFrom(Elysium) 
Insult.getsBuiltFrom(Elysium) 
Root = Card("Root") 
Root.getsBuiltFrom(Elysium) 
Root.getsBuiltFrom(Flow) 
Momentum.getsBuiltFrom(Flow) 
Shadow_Sword = Card("Shadow Sword") 
Shadow_Sword.getsBuiltFrom(Flurry_of_Blows) 
Reverse = Card("Reverse") 
Reverse.getsBuiltFrom(Flurry_of_Blows) 
Mighty_Weaponry = Card("Mighty Weaponry") 
Mighty_Weaponry.getsBuiltFrom(Fury) 
Furious_Cyclone = Card("Furious Cyclone") 
Furious_Cyclone.getsBuiltFrom(Fury) 
Starlight_Strike.getsBuiltFrom(Groundbreaker) 
Red_Mist = Card("Red Mist") 
Red_Mist.getsBuiltFrom(Groundbreaker) 
Breakthrough.getsBuiltFrom(Groundbreaker) 
Gut_Punch.getsBuiltFrom(Haymaker) 
Reverse.getsBuiltFrom(Haymaker) 
Serrated_Blade.getsBuiltFrom(Haymaker) 
Iron_Door.getsBuiltFrom(Immutability) 
No_Pasaran.getsBuiltFrom(Immutability) 
The_Collector.getsBuiltFrom(Knuckle_Crack) 
One_For_All.getsBuiltFrom(Knuckle_Crack) 
Lie_in_Wait = Card("Lie in Wait") 
Inspire = Card("Inspire") 
Inspire.getsBuiltFrom(Lift) 
Insult.getsBuiltFrom(Lift) 
Third_Law = Card("Third Law") 
Third_Law.getsBuiltFrom(Lift) 
Vigor = Card("Vigor") 
Vigor.getsBuiltFrom(Mad_Snack) 
Insult.getsBuiltFrom(Mad_Snack) 
Cardio = Card("Cardio") 
Cardio.getsBuiltFrom(Mad_Snack) 
Whack_em_All.getsBuiltFrom(Maim) 
Furious_Cyclone.getsBuiltFrom(Maim) 
Mighty_Weaponry.getsBuiltFrom(Offering) 
Double_edged_sword.getsBuiltFrom(Offering) 
Cauterize_Wound = Card("Cauterize Wound") 
Cauterize_Wound.getsBuiltFrom(Ox) 
Turtle_up = Card("Turtle up") 
Turtle_up.getsBuiltFrom(Ox) 
No_Pasaran.getsBuiltFrom(Pacifist) 
Iron_Door.getsBuiltFrom(Pacifist) 
Vigor.getsBuiltFrom(Padded_Shield) 
Third_Law.getsBuiltFrom(Padded_Shield) 
Cardio.getsBuiltFrom(Padded_Shield) 
Overwhelm = Card("Overwhelm") 
Overwhelm.getsBuiltFrom(Provoke) 
The_Collector.getsBuiltFrom(Provoke) 
Shield_Bite = Card("Shield Bite") 
Shield_Bite.getsBuiltFrom(Reckless_Charge) 
Starlight_Strike.getsBuiltFrom(Reckless_Charge) 
Red_Mist.getsBuiltFrom(Reckless_Charge) 
Save = Card("Save") 
Momentum.getsBuiltFrom(Save) 
Root.getsBuiltFrom(Save) 
Battle_Juice.getsBuiltFrom(Second_Wind) 
Readiness.getsBuiltFrom(Second_Wind) 
Overwhelm.getsBuiltFrom(Second_Wind) 
Storm_of_Blades.getsBuiltFrom(Side_Sword) 
Double_edged_sword.getsBuiltFrom(Side_Sword) 
Third_Law.getsBuiltFrom(Snap_Back) 
Root.getsBuiltFrom(Snap_Back) 
Breakthrough.getsBuiltFrom(Sticks_and_Stones) 
Red_Mist.getsBuiltFrom(Sticks_and_Stones) 
Cauterize_Wound.getsBuiltFrom(Tap) 
Doom = Card("Doom") 
Doom.getsBuiltFrom(Tap) 
Ambush = Card("Ambush") 
Ambush.getsBuiltFrom(Taunt) 
Doom.getsBuiltFrom(Taunt) 
Ambush.getsBuiltFrom(Weakest_Link) 
Riddle_of_Steel.getsBuiltFrom(Weakest_Link) 
Unleash = Card("Unleash") 
Unleash.getsBuiltFrom(Whirlwind) 
Furious_Cyclone.getsBuiltFrom(Whirlwind) 
Gut_Punch.getsBuiltFrom(Whirlwind) 
